<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Santri extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Santri_model');
    } 

    /*
     * Listing of santri
     */
    function index()
    {
        $data['santri'] = $this->Santri_model->get_all_santri();
        
        $data['_view'] = 'santri/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new santri
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_yayasan','Id Yayasan','required');
		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('email','Email','valid_email');
		$this->form_validation->set_rules('no_hp1','No Hp1','numeric');
		$this->form_validation->set_rules('no_hp2','No Hp2','numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_yayasan' => $this->input->post('id_yayasan'),
				'nama' => $this->input->post('nama'),
				'email' => $this->input->post('email'),
				'no_hp1' => $this->input->post('no_hp1'),
				'no_hp2' => $this->input->post('no_hp2'),
            );
            
            $santri_id = $this->Santri_model->add_santri($params);
            redirect('santri/index');
        }
        else
        {
			$this->load->model('Yayasan_model');
			$data['all_yayasan'] = $this->Yayasan_model->get_all_yayasan();
            
            $data['_view'] = 'santri/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a santri
     */
    function edit($id)
    {   
        // check if the santri exists before trying to edit it
        $data['santri'] = $this->Santri_model->get_santri($id);
        
        if(isset($data['santri']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_yayasan','Id Yayasan','required');
			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('email','Email','valid_email');
			$this->form_validation->set_rules('no_hp1','No Hp1','numeric');
			$this->form_validation->set_rules('no_hp2','No Hp2','numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_yayasan' => $this->input->post('id_yayasan'),
					'nama' => $this->input->post('nama'),
					'email' => $this->input->post('email'),
					'no_hp1' => $this->input->post('no_hp1'),
					'no_hp2' => $this->input->post('no_hp2'),
                );

                $this->Santri_model->update_santri($id,$params);            
                redirect('santri/index');
            }
            else
            {
				$this->load->model('Yayasan_model');
				$data['all_yayasan'] = $this->Yayasan_model->get_all_yayasan();

                $data['_view'] = 'santri/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The santri you are trying to edit does not exist.');
    } 

    /*
     * Deleting santri
     */
    function remove($id)
    {
        $santri = $this->Santri_model->get_santri($id);

        // check if the santri exists before trying to delete it
        if(isset($santri['id']))
        {
            $this->Santri_model->delete_santri($id);
            redirect('santri/index');
        }
        else
            show_error('The santri you are trying to delete does not exist.');
    }
    
}
