<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tagihan_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tagihan_master_model');
    } 

    /*
     * Listing of tagihan_master
     */
    function index()
    {
        $data['tagihan_master'] = $this->Tagihan_master_model->get_all_tagihan_master();
        
        $data['_view'] = 'tagihan_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tagihan_master
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_tagihan','Nama Tagihan','required');
		$this->form_validation->set_rules('keterangan','Keterangan','required');
		$this->form_validation->set_rules('jumlah','Jumlah','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_tagihan' => $this->input->post('nama_tagihan'),
				'jumlah' => $this->input->post('jumlah'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $tagihan_master_id = $this->Tagihan_master_model->add_tagihan_master($params);
            redirect('tagihan_master/index');
        }
        else
        {            
            $data['_view'] = 'tagihan_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tagihan_master
     */
    function edit($id)
    {   
        // check if the tagihan_master exists before trying to edit it
        $data['tagihan_master'] = $this->Tagihan_master_model->get_tagihan_master($id);
        
        if(isset($data['tagihan_master']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_tagihan','Nama Tagihan','required');
			$this->form_validation->set_rules('keterangan','Keterangan','required');
			$this->form_validation->set_rules('jumlah','Jumlah','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_tagihan' => $this->input->post('nama_tagihan'),
					'jumlah' => $this->input->post('jumlah'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Tagihan_master_model->update_tagihan_master($id,$params);            
                redirect('tagihan_master/index');
            }
            else
            {
                $data['_view'] = 'tagihan_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tagihan_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tagihan_master
     */
    function remove($id)
    {
        $tagihan_master = $this->Tagihan_master_model->get_tagihan_master($id);

        // check if the tagihan_master exists before trying to delete it
        if(isset($tagihan_master['id']))
        {
            $this->Tagihan_master_model->delete_tagihan_master($id);
            redirect('tagihan_master/index');
        }
        else
            show_error('The tagihan_master you are trying to delete does not exist.');
    }
    
}
