<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tagihan_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tagihan_detail_model');
    } 

    /*
     * Listing of tagihan_detail
     */
    function index()
    {
        $data['tagihan_detail'] = $this->Tagihan_detail_model->get_all_tagihan_detail();
        
        $data['_view'] = 'tagihan_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tagihan_detail
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_tagihan_master','Id Tagihan Master','required');
		$this->form_validation->set_rules('tanggal','Tanggal','required');
		$this->form_validation->set_rules('id_santri','Id Santri','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_tagihan_master' => $this->input->post('id_tagihan_master'),
				'status_pembayaran' => $this->input->post('status_pembayaran'),
				'id_santri' => $this->input->post('id_santri'),
				'jumlah' => $this->input->post('jumlah'),
				'id_pengurus' => $this->input->post('id_pengurus'),
				'tanggal' => $this->input->post('tanggal'),
            );
            
            $tagihan_detail_id = $this->Tagihan_detail_model->add_tagihan_detail($params);
            redirect('tagihan_detail/index');
        }
        else
        {
			$this->load->model('Tagihan_master_model');
			$data['all_tagihan_master'] = $this->Tagihan_master_model->get_all_tagihan_master();

			$this->load->model('Santri_model');
			$data['all_santri'] = $this->Santri_model->get_all_santri();
            
            $data['_view'] = 'tagihan_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tagihan_detail
     */
    function edit($id)
    {   
        // check if the tagihan_detail exists before trying to edit it
        $data['tagihan_detail'] = $this->Tagihan_detail_model->get_tagihan_detail($id);
        
        if(isset($data['tagihan_detail']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_tagihan_master','Id Tagihan Master','required');
			$this->form_validation->set_rules('tanggal','Tanggal','required');
			$this->form_validation->set_rules('id_santri','Id Santri','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_tagihan_master' => $this->input->post('id_tagihan_master'),
					'status_pembayaran' => $this->input->post('status_pembayaran'),
					'id_santri' => $this->input->post('id_santri'),
					'jumlah' => $this->input->post('jumlah'),
					'id_pengurus' => $this->input->post('id_pengurus'),
					'tanggal' => $this->input->post('tanggal'),
                );

                $this->Tagihan_detail_model->update_tagihan_detail($id,$params);            
                redirect('tagihan_detail/index');
            }
            else
            {
				$this->load->model('Tagihan_master_model');
				$data['all_tagihan_master'] = $this->Tagihan_master_model->get_all_tagihan_master();

				$this->load->model('Santri_model');
				$data['all_santri'] = $this->Santri_model->get_all_santri();

                $data['_view'] = 'tagihan_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tagihan_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting tagihan_detail
     */
    function remove($id)
    {
        $tagihan_detail = $this->Tagihan_detail_model->get_tagihan_detail($id);

        // check if the tagihan_detail exists before trying to delete it
        if(isset($tagihan_detail['id']))
        {
            $this->Tagihan_detail_model->delete_tagihan_detail($id);
            redirect('tagihan_detail/index');
        }
        else
            show_error('The tagihan_detail you are trying to delete does not exist.');
    }
    
}
