<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Yayasan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Yayasan_model');
    } 

    /*
     * Listing of yayasan
     */
    function index()
    {
        $data['yayasan'] = $this->Yayasan_model->get_all_yayasan();
        
        $data['_view'] = 'yayasan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new yayasan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
            );
            
            $yayasan_id = $this->Yayasan_model->add_yayasan($params);
            redirect('yayasan/index');
        }
        else
        {            
            $data['_view'] = 'yayasan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a yayasan
     */
    function edit($id)
    {   
        // check if the yayasan exists before trying to edit it
        $data['yayasan'] = $this->Yayasan_model->get_yayasan($id);
        
        if(isset($data['yayasan']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
                );

                $this->Yayasan_model->update_yayasan($id,$params);            
                redirect('yayasan/index');
            }
            else
            {
                $data['_view'] = 'yayasan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The yayasan you are trying to edit does not exist.');
    } 

    /*
     * Deleting yayasan
     */
    function remove($id)
    {
        $yayasan = $this->Yayasan_model->get_yayasan($id);

        // check if the yayasan exists before trying to delete it
        if(isset($yayasan['id']))
        {
            $this->Yayasan_model->delete_yayasan($id);
            redirect('yayasan/index');
        }
        else
            show_error('The yayasan you are trying to delete does not exist.');
    }
    
}
