<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tagihan_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tagihan_master by id
     */
    function get_tagihan_master($id)
    {
        $tagihan_master = $this->db->query("
            SELECT
                *

            FROM
                `tagihan_master`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $tagihan_master;
    }
        
    /*
     * Get all tagihan_master
     */
    function get_all_tagihan_master()
    {
        $tagihan_master = $this->db->query("
            SELECT
                *

            FROM
                `tagihan_master`

            WHERE
                1 = 1

            ORDER BY `id` DESC
        ")->result_array();

        return $tagihan_master;
    }
        
    /*
     * function to add new tagihan_master
     */
    function add_tagihan_master($params)
    {
        $this->db->insert('tagihan_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tagihan_master
     */
    function update_tagihan_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tagihan_master',$params);
    }
    
    /*
     * function to delete tagihan_master
     */
    function delete_tagihan_master($id)
    {
        return $this->db->delete('tagihan_master',array('id'=>$id));
    }
}
