<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Yayasan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get yayasan by id
     */
    function get_yayasan($id)
    {
        $yayasan = $this->db->query("
            SELECT
                *

            FROM
                `yayasan`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $yayasan;
    }
        
    /*
     * Get all yayasan
     */
    function get_all_yayasan()
    {
        $yayasan = $this->db->query("
            SELECT
                *

            FROM
                `yayasan`

            WHERE
                1 = 1

            ORDER BY `id` DESC
        ")->result_array();

        return $yayasan;
    }
        
    /*
     * function to add new yayasan
     */
    function add_yayasan($params)
    {
        $this->db->insert('yayasan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update yayasan
     */
    function update_yayasan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('yayasan',$params);
    }
    
    /*
     * function to delete yayasan
     */
    function delete_yayasan($id)
    {
        return $this->db->delete('yayasan',array('id'=>$id));
    }
}
